sudo: required
dist: trusty
language: c
osx_image: xcode8
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
addons:
  apt:
    packages:
      - xz-utils
      - icnsutils
      - graphicsmagick
install:
  - nvm install 6
  - npm install
  - npm prune
script:
  - npm test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
