sudo: required
dist: trusty
language: c
osx_image: xcode8
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
addons:
  apt:
    packages:
      - xz-utils
      - icnsutils
      - graphicsmagick
      - rpm
install:
  - nvm install 6
  - npm install
  - npm prune
script:
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run pack:macos; fi
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf dist/linux-ia32-unpacked && rm -rf dist/linux-unpacked; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf dist/Tusk-darwin-x64; fi
deploy:
  provider: releases
  api_key:
    secure: "y8Rakg0DpSL9Y53E1N9mDWfd4G3crJoEqc3jU8zGlmWh7d0fwCfDg84fMaZUsoVes8cWxIuOX0Wq1SEDghSEVpzhJRULtziAEj0SxjEpGdG1kYdGg/wzBJOF/PxcV3aka5/3h77YW/kYEGHNwKUjbFFPckqTfWqnu3Eqmg1bOr87ufgzX7xLPs9KF2rLAVFQSZqqw6LdZ0QPsHHtlYuiD8HM23BN5GPRTle3NMBfTYpWplDU+qx3ehYDVs8DFZn2mQOs0IQVBXrG/csVSlY8gj87/215bQCvUKJt9tgQl1vSD8wWGrxpTfWpkuLRQNOUlNBKQvHKjHYFRntIXMBm1oTZMMU0qxhE1gmC2MVsKrMauedH1IPa4yybI7iL6h/WIF8+73SQ0aAjjyyz8wakSq0foHp5MkucaEz8lQMBApC07fzzmmwcy/nf80vewpbUuCboQhsfqsVXA1zjqXiGbz2Xz7Wpi9yQ4JXEg5cYPNBawgF4OzEpqCwJm8LbtmT0nQGGCYeGkv24Rzm8l6mk+ewqb8uVoNNOwGt7DZ4fZP62ES1rJ3v75O0bbjmoQ9HJ9eziHY09q+1Et/ufRGX5cN8cfgS+KuL4YmmXh90tHBTvvpGLL8X1Q8QCmrBeGaSZ5QOtSWB3HH0AsYKRUYWvEpz4HraaYqLO3xV30Y5LKws="
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
