sudo: required
dist: trusty
language: c
osx_image: xcode9
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
addons:
  apt:
    packages:
      - xz-utils
      - icnsutils
      - graphicsmagick
      - rpm
install:
  - nvm install 6
  - npm install
  - npm prune
script:
  - npm test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run pack:macos; fi
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf dist/linux-ia32-unpacked && rm -rf dist/linux-unpacked; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf dist/Tusk-darwin-x64; fi
deploy:
  provider: releases
  api_key:
    secure: "pvEq2vy4EqJ8O/ttqZXmibUFJSgNR1qZhzZzA6Fsh6fVnwOzTrNvJPUduDj3g/Hhi5K9XwsPixSDdFLiFBuYWX7JrD0Y8cx8Ma3/kdKIYtwgwFPvv3mo/7wOLI/zjE56hF+SeMRlLsOM7AWRA5hheEgzChZRiZh6DSmQerh2Y22GPiLHYvmAmt4I0QkUNkLygFDcKY2p8nu+DccYZOYK7ZaxfFFLzUvGK8ibtCCOmoULTWFqETV2H3YkJ38yIt3Tm1yxOxeFsX5uqlzX02kUUO6rlsGBhoupQHQWmZfdkU95ALwNjlIi6gVC+0cDL98pBx86F6yeSNaf8Rx0qUBEWeb6GxhG8BCtlQYmgs4Ats7voKDIigDoSV2OX8G4kELEU0xiGBBrgYZ393kx/hkeYzDTGyZ1SOetS7QJeSX4Bhb9X/oSP+69Xpopor1HAyVEADg2haajSrFW/Jpk2rDjyrYlpl+3BYqNWi49sPQ+1czU/j/4O5WxPGlyfcLo6DunTorKI92zT5uS5xQ5NKzTMTIQC2Tc+29kFaHUIG5d8p3uPTNEbJS8OWJyMuI7Efj1OR/VRgtd0sEwM9qIWWYpsI378vr5bKzoPAUKU71ICzhDZC8jXdCvld+I8tN7jM9/f6tr2XKoHXYyo9sUPEfU1FNay2kI9cuFy3tXTPh6UjI="
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
