platform:
  - x64
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 6 x64
  - npm install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm --version
  - node --version
  - npm install
  - npm prune
build_script:
  - npm test
  - npm run dist
deploy:
  description: 'Tusk - Refined Evernote desktop app'
  provider: GitHub
  auth_token:
    secure: vS3PbROPIEs5ZGaeK7vLTojdSbM33G8cLknTV5OBUDt/utMNiBv9UmrZnuNqR96E
  artifact: dist\win\tusk-app-0.3.0-full.nupkg, dist\win\RELEASES, dist\win\Tusk Setup 0.3.0.exe
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
shallow_clone: true
