platform:
  - x64
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 6 x64
  - npm install -g npm
  - npm install
build_script:
  - npm test
  - npm run dist
shallow_clone: true
