platform:
  - x64
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 6 x64
  - npm install -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm config set unsafe-perm true
  - npm --version
  - node --version
  - npm install
  - npm prune
build_script:
  - npm test
  - npm run dist
shallow_clone: true
